### ISSUE TITLE
AutoUpdater for private repo

### ISSUE THREAD

**Issue by abhishek-h-sharma** [juampi92/auto-updater#1]
I am creating a `Node-webkit` app for which I need to integrate auto-updater.  
`auto-updater` is working fine with public repo. How should I make it work for private repo?  
Where should I provide credentials for my Github repo?

**Comment by juampi92** [comment]
Oh, i have no idea because i've never made a private repo, but the thing is that you'd have to log in with some kind of credentials that could make the reading of your private repo available to anyone...

I recommend you checking the github api https://developer.github.com/
If you come up with something, i'm willing to help you.

Good Luck!
Juampi.
